language: python
python:
- '3.6'
services:
  - postgresql
addons:
  postgresql: "10"
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- pip install model_mommy
script:
- python manage.py test
env:
  - DATABASE_URL=postgres://postgres:@localhost
deploy:
  provider: heroku
  app: pyconbalkan
  api_key:
    secure: QBsudP8boijk2p+H0gx3zvijhfOm18lHfpFQYNP+bD31+vuNaW8Cu5UTbxHsRJezoIs8zZArkQ0KGCTsnZTK2wRwhI2BKKj2HD3nl26jxyeglkAdXg+/uffJLC7ezWXgBB8XXfXQQrRqZZr7T85g+t/j4ibgTJkYsmZUnQJ9Q+m1bYlaRj9+5F1CumGVUwpirx9UXSv62Zc3CBT+mOdKMxVK1YlHkeX5mV3N0GbmLxgIvM5qTndve7gLhhxic1I5549szJt+jDJnTZBhA4e2qFRNS/RsYhuhZ2VsQSgcuvtwTbetDGa76lUQ5ri6FqWI1n/toanQzXRQJrdl27HzBGwg0ebFy+OmTxDklauDeDe9CD4hA4XSGQ8GU0pZrdbDr3ZjnDlx1E8c2PqnBkVoN4KKkPxw3FESxn4rc2+tmPwgde9mG/2TDaQ6E5Xe0OL6k8bDCon1kV4DyLMD4rbViMSy7XNuYiWsXTurohK4AKgSLaCujDXYpWzBbghSYtNP4J0SxJdhzyZnGORPr7rAMAWtUFs16AJAYmOnF7uxPDUC0ml2bG391LnUNjGkJz75e44d9ZZkpjLudDbu+B58BPfULnpJDRs0N8YK//MJD/dn49II496PlO9kHvQ+D/p40Jtwqt64O4rk+9GCecs2rPf4FTZa0+dRFa1rWDjta6c=
