language: python
python:
- '3.6'
services:
- postgresql
addons:
  postgresql: '9.6'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- pip install model_mommy
script:
- python manage.py test
env:
- DATABASE_URL=postgres://postgres:@localhost/test
deploy:
  provider: heroku
  app: pyconbalkan
  api_key:
    secure: eZx87paHEYM3HzEDFXLjhKPJHblZ2ptt73yuuXcQBgMrClJ/nz2uOre813TYb5VNMACO7vLtuAhAsT+934Dtqi1zf9Tg9BR8U2jVazoUdauX4eH9xt7podOL2cJ796/nkc+DkEZyPgF3Saxd9d4PIWvkXYvpLXkMaGI41H2Iss52aNgqvG+HmDRmk3u7Pr7ZJbKkjP3QI/P5qM2ISfCS7XDK3FqvZ8hMcEvcxZHm6A0mjiim1c6dhtvtCRJPMfBkP/cZ8RdyxHsZfKJ7mY0I+9q+UDUW4nhfGFQ0zqaWhISL0764CtLR5oaR05bTMgjzKtXipj/Iy7V2f/lonJoQkv48R+RvUO5zn4ifsuAIkW2WQHozK8spctodjmn+cba5V2D2nPz68nSGKoQPJzt9fAzWrW3EcMteRmVQEhpXSPs2Y1za1NDVQ2O3nt8+ImClow46nWQn/oA6YvQ/dE0c15YAD+RBemm+l6elS0kBvV8LBhDxWullTchBlZ6uzsVM5UfiYH/eA9Mqb9GkpPgJ2cUB9auvJe66+Mph8JGtw8wVIDwj5N/c2hXnmi9ajWm5V3Ku0DOhrK/8tryHnsawbJ6VDpm4Ye2RgofZcmaobhgJXqrS+C+zqLxIvqeVBlJ9U6ugqCD6G2JRujg/o7CBa5nwyH/Dt6ZRd6VvkwOSN5k=
